apiVersion: v1
kind: ServiceAccount
metadata:
  name: civiclens-ksa
  namespace: civiclens
  annotations:
    # Liaison Workload Identity avec le Google Service Account provisionné par Terraform (Temps 1)
    iam.gke.io/gcp-service-account: "wh-djvagl-gke-app-sa@wh-djvagl.iam.gserviceaccount.com"
